### ISSUE TITLE
Make SeparateTextGUIThread a public class

### ISSUE THREAD

**Issue by jcfrei** [mabe02/lanterna#158]
Is there a reason why SeparateTextGUIThread is not a public class? I find myself using the class in my own project and use lanterna as a library like this:

SeparateTextGUIThread guiThread = (SeparateTextGUIThread)textGUI.getGUIThread();

**Comment by avl42** [comment]
I had a look at it, and found no reason not to make it public, but instead a rather strong reason to indeed make it public: namely that TestBase in the test tree of Lanterna uses it, and it can do so only because it is in the same "package" c.g.l.gui2 within the test tree.

Apart from that, I noticed some possible concurrency issues, where two member variables of the class are accessed also from within the textGUIThread, but these members are not synchronized in any way. That means that the textGUIThread might see neither the new waitLatch nor changes in the status.  To fix that, these members should at least be volatile, and I'm positive that this is already enough.  PR will follow soon...

**Comment by mabe02** [comment]
I've refactored this a bit, if you want a separate thread to run the GUI event loop, you can do this:
    AsynchronousTextGUIThread guiThread = (AsynchronousTextGUIThread)textGUI.getGUIThread();
    guiThread.start();
    ...
    guiThread.waitForStop();

**Comment by avl42** [comment]
post-close note: yes, that extra bit of polishing was a good one, thanks!
