### ISSUE TITLE
Virtual screen and components size measures.

### ISSUE THREAD

**Issue by dant3** [mabe02/lanterna#163]
I have a gui app with following layout:
```
+--[ main window   ]---------------+
|  toolbar                         |
+----------------------------------+
|  listbox with long strings       |
+----------------------------------+
   ↑
   +-- LinearLayout(orinetation = Vertical)
```
See screenshot for example.
Then my listbox has very long strings inside it's size measure tells that it want this hige amount of columns of terminal. As I see it, screen area stretches itself making whole terminal a big scrollable area. This doesn't looks like a convenient behaviour. Issues I see here are:

1. scrollable screen area doesn't looks like a general usecase.
I see very limited convenient usages of it. If we would look at alternatives in non-terminal gui apps, I know only one very special case groups of apps which uses full-window scrolling (notice - not the screen scrolling - only particular window) - like photo editing tools or music editors.

2. LinearLayout behaviour seems strange. I understand why it could recommend window to become bigger if it's not yet fits whole screen space, but I don't understand why it recommends taking even more space.

One more interesting thing is vertical scrollbar I see nearby listbox. Not sure what it displays, but looks really odd.

![image](https://cloud.githubusercontent.com/assets/820057/8871576/136cee42-31ff-11e5-916d-b167de71e559.png)

**Comment by avl42** [comment]
The "proper & general" way would be to have each component not only have a preferredSize, but also a minimumSize, and trigger VirtualScreen's scrolling only based on total minimumSize, rather than on preferredSize.

In the meantime you really should override listbox's getPreferredSize method to return a smaller size.

**Comment by dant3** [comment]
But how can I define it such that it fit the free space of my window? Should I access parent child's to calculate it? It sounds odd. I expect it as a parents layout manager job, to get all the preferences and put them together so that all child's would be happy and fit parent's size behaviour as well.

**Comment by avl42** [comment]
The layout manager asks its children about their preferred sizes (and if a Panel is among them, then it again asks its own children, etc).  In the end, there is a size that a particular Window "wants", and this size is taken to define VirtualScreen's minimal size.

For now (and that is rather meant as a test, than as a solution) further subclass the listbox-variant you use and override method getPreferredSize() to return a hardcoded small {20x5} size.  See if this gets rid of the scrollbars, and also see if the listbox really ends up exactly that small size, or whether it already gets some extra space.

In the ideal case, the listbox will get extra space despite its modest wishes.
Otherwise, see, if you can setLayoutData your listbox to Alignment.Fill (needs some extra code).
Otherwise again, there'll be a need to modify LinearLayout to pass on available extra space also along the direction of the layout.

**Comment by avl42** [comment]
PS: if you do the getPreferredSize-change and that doesn't solve it, then please post a new screenshot.

**Comment by dant3** [comment]
So, I've made a couple of attempts as you suggested:
1. Made explicit prefered size: ```setPreferredSize(new TerminalSize(20, 5))```

![image](https://cloud.githubusercontent.com/assets/820057/8874192/2c41899c-3217-11e5-9053-207d4c62020e.png)

2. Added ```setLayoutData(LinearLayout.createLayoutData(LinearLayout.Alignment.Fill))``` to it

![image](https://cloud.githubusercontent.com/assets/820057/8874173/06cb563e-3217-11e5-947b-4c04961a18e9.png)

My window returns set of ```Window.Hint.FIT_TERMINAL_WINDOW, Window.Hint.NO_POST_RENDERING``` as it's `getHints` result

**Comment by avl42** [comment]
I see, thanks for the screenshots.
Next hurdle is to get the window full-sized, even if it believes that its contents don't need that space.
Apparently it ignores Window.Hint.FIT_TERMINAL_WINDOW which surprises me a bit. 
Do you really need the "Catlog" as a Window, or could you also add the components to MultiWindowTextGUI's getBackgroundPane(), maybe with an extra Border for the Catlog-frame.

**Comment by avl42** [comment]
PS: ok, I know, why FIT_TERMINAL_WINDOW didn't do it: it only limits the maximum size to the screen size but doesn't expand the Window beyond its preferredSize.
In your original code the screen size (well, the virtual one) had already been expanded for the big listbox's preferredSize...

What remains is the suggestion for using backgroundPane for your components, if possible.

**Comment by dant3** [comment]
Ultimately I'd love to make a split screen feature in the future, where multiple listboxes (ultimately tables wtih dymanic scrolling content and color highlighting) show output from multiple devices. I fought windows would be a good fit for it. It might imply that I'll do custom tiling window manager of course.
Anyway, I use window currently to put things together as I just started development with Lanterna 3, and I didn't found which way works better yet. I was asking about how would I kickoff ui eventloop explicitly to make things spin, and not sure how to do this then you have no windows initially. Eventually I show some dialogs, like if you'll press F1 you'll get device selection box. In alpha-6 I was able to do start eventloop through `getGuiThread.start()`, but this doesn't work anymore that way. I guess I could use custom ui thread instead of main one, but any better solution would be awesome.

**Comment by avl42** [comment]
Using backgroundpane wasn't meant as solution, but just to check, if a larger "window" would give the extra space to the components.  The backgroundPane is like a force-maximized Window.

if it does, then next step could be your tiled window manager (and your components would then go back into Windows, whose size you set from outside, rather than having them choosing their own size).

If it doesn't, then more work lies ahead, and you might instead choose to roll back everything from this thread, and instead patch the MultiWindowTextGUI to not use the VirtualScreen.

**Comment by dant3** [comment]
I've tried to move my listbox as the background. This indeed works as I would wish window to behave:
![image](https://cloud.githubusercontent.com/assets/820057/8885726/fcf3d2c2-326a-11e5-8395-62f2534949fe.png)

**Comment by dant3** [comment]
Now thats interesting. I've implemented preferredSize like this:
```scala
  override def calculatePreferredSize() = {
    screen.getTerminal.getTerminalSize.withRelative(-6, -6)
  }
```
And here is the result (notice screen overflow scrolling):
![image](https://cloud.githubusercontent.com/assets/820057/8886180/38e314ba-326f-11e5-9332-4285b3943ca6.png)
I also tried to override getSize similarly, without any visual changes.

**Comment by avl42** [comment]
Have a look at how MultiWindowTextGUI translates the window's preferredSize to its VirtualScreen's setMinimumSize. :-)

**Comment by mabe02** [comment]
So, take-away points here that I can see:
 * Full-screen windows (not so hard)
 * Resize virtual screen based on minimum size instead of preferred size (tricky)

**Comment by avl42** [comment]
Maybe that just went without saying, but I say it anyway:  Full-screen windows, to whose size the MultiWindowTextGUI will *not* add those extra 5 rows and 10 columns :-)   Actually, I think, that the decision about all windows' size-demands on the screen should be WindowManager's concern, not TextGUI's.

Yes, I also expect the minimum-size feature to be quite tricky... as it requires a getMinimumSize() method in each and every component, and further complicates the size "negotiations"...

**Comment by mabe02** [comment]
Hmm, what about the VirtualScreen in MultiWindowTextGUI? I'm thinking of lifting it out, either completely or make a subclass of MultiWindowTextGUI that adds it on, so it's optional.

**Comment by mabe02** [comment]
The 5x10 thing was probably never intended to be used, I think it was a placeholder that was forgotten. I've replaced it now with some code that will just look for the bottom-right corner of all windows and the maximum value as the VirtualScreen's minimum size.

**Comment by mabe02** [comment]
OK, also added a FULL_SCREEN window hint and implemented it. Added tests to the window manager test class and it seems to be working nicely (although uncovered a different bug in BorderLayout)
