### ISSUE TITLE
Threading model?

### ISSUE THREAD

**Issue by drozzy** [mabe02/lanterna#197]
I want to run lanterna as a gui for my actor system - what kind of threading model does it require?

Should I spawn it in a separate execution context (scala term)?

Any tips appreciated.

**Comment by avl42** [comment]
Since nobody answered so far, I'll do... I don't understand the question.
I don't know about Scala and its "execution contexts"...

Maybe if you mention some possible "models", I or someone else might answer with some pros&cons for each.

**Comment by mabe02** [comment]
Hi @drozzy, in general, Lanterna should be thread-safe, so updating through multiple threads should be possible. Please note that using the low-level Terminal layer with multiple threads, although allowed by lanterna, is guaranteed to cause strange output since the characters won't be written to stdout/stderr in a deterministic fashion. Also with Screen and TextGUI, you probably want to do some sort of periodic synchronization on the refresh/flush operation but in general you should be able to modify state concurrently.

If you do encounter race conditions or other problems with concurrency, please open an issue here and let us know how to reproduce.
