### ISSUE TITLE
AbstractTextGUIThread.invokeLater should actually invoke later

### ISSUE THREAD

**Issue by stephentalley** [mabe02/lanterna#208]
Commit 1293d01 changed the default behavior of AbstractTextGUIThread.invokeLater():

        @Override
        public void invokeLater(Runnable runnable) throws IllegalStateException {
    -        customTasks.add(runnable);
    +        if(Thread.currentThread() == getThread()) {
    +            runnable.run();
    +        }
    +        else {
    +            customTasks.add(runnable);
    +        }
        }

Now if you are on the UI thread, and need to schedule (but not immediately invoke) a task on the UI thread, you have to resort to creating a separate thread to call invokeLater()!  That is not consistent with javax.swing.SwingUtilities.invokeLater() or EventQueue.invokeLater(), which unconditionally queues the Runnable to run after all other scheduled tasks.

The behavior was correct prior to 1293d01.  I think that commit should be reverted.

If this new behavior is really needed (and not already handled by invokeAndWait() or AbstractComponent.runOnGUIThreadIfExistsOtherwiseRunDirect()), can you please add a new method with the old behavior?

Thanks!

**Comment by avl42** [comment]
FWIW, I agree. After all the method is called invoke**Later** :-)

I hope Martin will tell us, what was his motivation already 1½ years ago, when he conceived the specification of method `invokeLater()` in commit c3ea64596dec395e9773cb3579b180df40245a84 .

My guess is, that `invokeLater()` was thought of just a workaround for multi-threaded applications, to get stuff run in the GUI thread, so that workaround wouldn't be necessary in single-thread mode, or if already on GUI-thread.  But there are indeed cases, where one just wants to set up things to be done later, even if the thread is already the only/right one - e.g. to avoid stack-intensive recursion.

**Comment by mabe02** [comment]
Yeah, the purpose was to ensure the code was run on the same thread that was managing the GUI. We can clarify this.

**Comment by avl42** [comment]
still there is also this other usecase of invoking something later, that
invokeLater would just fit so much better. maybe the current invokeLater
should rather be invokeInGuiThread then...

**Comment by mabe02** [comment]
I think there was some deadlock that would happen before when you called the invokeLater while being on the GUI thread, but changing the library for that might not have been the correct approach

**Comment by mabe02** [comment]
Not sure if there's any value to adding invokeNowOrLater(..) that will run the code immediately if on the GUI thread and later if not?

**Comment by mabe02** [comment]
Pushed c06bde063b539782d86f4a0277c655cde34aa016 the inverts the thread checks for invokeAndWait and invokeLater, so that invokeLater always fires later

**Comment by stephentalley** [comment]
Thanks Martin.  This fix looks good.
