### ISSUE TITLE
TerminalTextUtils.getWordWrappedText infinite loop and crash

### ISSUE THREAD

**Issue by jslater89** [mabe02/lanterna#209]
(Great library—I'm using it to render a terminal-based board game implementation, and it's cool to see it being actively maintained.)

getWordWrappedText fails in bad ways for two cases:

1. If text is "", it throws an exception, when it should probably return {""}.
2. If maxWidth is 0, it never breaks out of the loop, and should probably throw an exception.

**Comment by avl42** [comment]
I don't see any exception for "", but I do see the infinite loop with maxWidth==0

Not sure, though, if throwing an exception is best. If maxWidth<=0 then I'd see these alternatives:
1.  don't break lines at all - just return the input unchanged.
2.  just set maxWidth to 1 instead.
3.  throw IllegalArgumentException.

I can only guess that wrapping at 0 happens as a side-effect of making some textbox/label/... too narrow. Then that should be rather handled like the cheapest possible "no-op", because most likely nothing will be visible of those lines, anyway.  I wouldn't want an application to crash with an IllegalArgumentException, just because the user resized the Terminal too narrow.

**Comment by jslater89** [comment]
Yes, that was the case I saw it in. You make a fair point about how to handle it.

I may have been confusing "" with a null string—I'll build a little test case and see.

**Comment by avl42** [comment]
Well, if you pass null for the lines, then a NullPointerException seems
reasonable to me.

Now, we can only wait for @mabe02 -- but you could write up a PR, even if
just for that one maxWidth check.

**Comment by avl42** [comment]
seems like that previous reply through email broke.

I meant to add that we can now only wait for @mabe02, but if you prepare a simple PR for that one check, then Martin will have even a bit less work with it.

**Comment by mabe02** [comment]
Hmm, maxWidth <= 0, maybe just do no line breaking at all then to simplify

**Comment by mabe02** [comment]
Ok, pushed 4aabc75a42bd09fdf408b9dca16da1d84534b635, hopefully that will fix it!
