### ISSUE TITLE
tutorial 1 problem (solved)

### ISSUE THREAD

**Issue by WhiteDruid** [mabe02/lanterna#317]
hello sir , i have a problem with tutorial 1 example . 
http://uupload.ir/files/gav_2017-07-17.png
can you tell me where is the problem and how i can fix it ? thank you

**Comment by avl42** [comment]
The yellow wavy lines on lines 3-5 seem not to align with words, so maybe
eclipse simply needs a refresh (usually with F5 Key) or "Clean all" and
rebuild all.

Another thing to check is hover the mouse above the word "Terminal" on line
13 and see if the tooltip shows the correct class.

A third thing is, that (if I'm not mistaken) there is/are already beta
versions of lanterna-3.0.0, while you seem to be using still alpha3 - I'd
suggest fetching latest version and let eclipse use that instead of -alpha3.

I hope any of that helps.

**Comment by WhiteDruid** [comment]
hi sir thanks for helping . http://uupload.ir/files/rzcf_2017-07-17_(1).png 
i solved problem . 
i used lanterna 3.0.0 beta3 Instead alpha

**Comment by avl42** [comment]
One afternote:  if you clicked tbe "Problems" tab in the lower right pane,
or if you let your mouse hover above the wavy red lines, then eclipse might
tell you what it thinks is wrong.  Usually that's quite valuable, but given
the strange yellow lines, I wouldn't expect much from it in this case,
unless eventually the yellow lines disappear and the red ones remain.

**Comment by Janrupf** [comment]
Hey, maybe this issuise should be closed (cause its solveld)

**Comment by WhiteDruid** [comment]
close

**Comment by WhiteDruid** [comment]
how i can close it ?
