### ISSUE TITLE
Progress Bar Refresh before/after Thread.sleep

### ISSUE THREAD

**Issue by keenoar** [mabe02/lanterna#347]
I was trying to create a dummy progress bar, so I defined the following:

```
ProgressBar pb = new ProgressBar(0, 100, 100);
pb.setPreferredSize(new TerminalSize(100, 1));
pb.setLabelFormat("Progress");
pb.setValue(0);
panel.addComponent(pb);
```

Then in a button, I created a dummy update for the progress bar (sleep) - adding screen.refresh() did not have any effect:

```
panel.addComponent(new Button("Submit", ()->{
    for (int i = 0; i <= 100; i+=25) {
        try{
            pb.setValue(i);
            pb.setLabelFormat(String.valueOf(i));
            screen.refresh();
            Thread.sleep(500);
        }
        catch (Exception e) {
            e.printStackTrace();
        }
    }
}));
```
The progress bar does not get updated on the screen. If it was set in another thread, it will refresh like this without the need of refresh() to be called:

```
panel.addComponent(new Button("Submit", () -> {
    new Thread() {
        public void run() {
            for (int i = 0; i <= 100; i+=25) {
                pb.setValue(i);
                pb.setLabelFormat(String.valueOf(i));
                try {
                    Thread.sleep(500);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }.start();
}));
```
Thanks,

**Comment by mabe02** [comment]
Hi @keenoar,
The threading model has a single thread responsible for drawing the GUI and the same thread is used when running events registered to interactable components. This is exactly the same as how AWT/Swing works. What you are doing above is to block this thread since you are doing it in the Button's callback, so the GUI rendering isn't running. The `screen.refresh()` calls into the buffered screen layer that is one level below what the GUI works on, so for various reasons this won't do what you want.

Ideally, you should try to mutate GUI components on the GUI thread (just like AWT/Swing) but they usually work even if set by a separate thread like you're doing above. When a GUI component is updated, it's marked as 'invalid' which makes the GUI system immediately try to redraw the screen (assuming the thread isn't held up somewhere). This is why your second attempt worked.

The basic rule is, don't block in event callback (except when displaying modal GUI dialogs) and run GUI code on the GUI thread (use `TextGUIThread#invokeLater(..)` to schedule things on the GUI thread).
