### ISSUE TITLE
Release 3.0.x?

### ISSUE THREAD

**Issue by MartyIX** [mabe02/lanterna#368]
Hi,

there are several bugfixes since 3.0 release. Would it be possible to make a new release?

Regards,
Martin

**Comment by avl42** [comment]
there are also still a few fixes committed on master branch that imho
should go into release/3.0

Maybe i get to write a rebasing PR, or I just list the files with diffs
between release/3.0 and master that I really think need backmerge...

Martin Vseticka <notifications@github.com> schrieb am So., 20. Mai 2018,
10:38:

**Comment by mabe02** [comment]
It's probably time to release a new version

**Comment by MartyIX** [comment]
@avl42 I know, but it doesn't have to be perfect. It is possible to release 3.0.1 and 3.0.2 for example..

I'm asking because I've been waiting for this https://github.com/mabe02/lanterna/issues/325 to be released for some time.

**Comment by mabe02** [comment]
Actually, I can't release right now as I'm out of business travels and I need my GPG keys at home for the Maven release. So by the end of this week, stay tuned...

**Comment by avl42** [comment]
Since we have one week, anyway, here is my summary of commits that I think should go to release/3.0 as well:

- https://github.com/mabe02/lanterna/commit/f064c4718f739e218e8504a60325949bcec5e75d  (#335)
   - docs/using-terminal.md
   - src/main/java/com/googlecode/lanterna/terminal/DefaultTerminalFactory.java

- https://github.com/mabe02/lanterna/commit/e5200a3d9c4e8070f1360b51716e471db6ee5161
   - docs/using-terminal.md
         
- https://github.com/mabe02/lanterna/commit/fc05487acc0609733fcbb5c30176cab015bde869 (#332)
   - src/main/java/com/googlecode/lanterna/terminal/ansi/TelnetTerminal.java
   - src/test/java/com/googlecode/lanterna/terminal/TelnetTerminalTest.java

This was gathered from skimming through ```git diff release/3.0 master``` and for each change looking up the commits.

**Comment by mabe02** [comment]
Yes, let's wait for the DPI thing and then release it

**Comment by psborges84** [comment]
@mabe02 @avl42 has a release date of the new version with bug fixes? the framework can not stop.

**Comment by jrb0001** [comment]
@mabe02 "the DPI think" is ready to be merged, is there anything else targeted for the next version?

**Comment by mabe02** [comment]
3.0.1 released!
