### ISSUE TITLE
Tab character in label truncates the end of text

### ISSUE THREAD

**Issue by lolo101** [mabe02/lanterna#376]
Tabulation character is rendered as multiples (typically 4) spaces characters.
However it counts as a single character when calculating the label's bounds, leading to the last (usually 3) chars of the label to be truncated.

**Comment by avl42** [comment]
My expectation was, that Label does size calculation well considering tabs.
So, lets try to find out, why it doesn't seem to work for you, or if my
look in the sources was just too cursory.

First thought is about any override of "TabBehaviour". (the default should
be fine, but if you override it explicitly to a particular mode (namely to
IGNORE), it might just show these symptoms.

Otherwise it might be helpful, if you could either show a small test
program, or at least supply the string that your Label should show (in Java
syntax: with \t, maybe \n, etc) for an attempt to reproduce it.

**Comment by lolo101** [comment]
Actually the tab is converted as 4 spaces, as expected. The issue is the space reserved for the label is calculated *before* the tab conversion leading to insufficent space reserved and the truncature of the tail of the text.

Here is an exemple :
```java
import java.io.IOException;
import com.googlecode.lanterna.gui2.*;

public class Main {

	public static void main(String... args) throws IOException {
		Screen screen = new DefaultTerminalFactory().createScreen();
		screen.startScreen();
		MultiWindowTextGUI gui = new MultiWindowTextGUI(screen);
		Window window = new LabelWithTabWindow();
		gui.addWindow(window);
		gui.waitForWindowToClose(window);
		screen.stopScreen();
	}
}

class LabelWithTabWindow extends AbstractWindow {

	LabelWithTabWindow() {
		Panel panel = new Panel();
		panel.addComponent(new Label("A label without tab"));
		panel.addComponent(new Label("\tAnd one with tab"));
		setComponent(panel);
	}
}
```
And how it is displayed on my PC :
![capture](https://user-images.githubusercontent.com/555864/41527509-b4499b72-72e7-11e8-8c20-cb40e0548372.PNG)
See how the last "tab" word is truncated on the second label.

**Comment by mabe02** [comment]
I'm kind of tempted to modify the `Label` class so it replaces tabs with four spaces up-front when you set the string. Otherwise, we'd need to modify `TerminalTextUtils` so we can tell it what tab behavior to use when measuring the text length and it can get really complicated. But, if we do this for label, we probably need to also do this for all other other classes that take in strings that are displayed...

Any thoughts?

**Comment by lolo101** [comment]
I'm intuitively tempted to modify `TerminalTextUtils` as you suggest, since there already is code to handle CJK chars, that seems quite consistent to me. Furthermore it looks like many (all ?) component that display strings end up calling this method to calculate their preferredSize or bounds.

**Comment by mabe02** [comment]
I've updated the TerminalTextUtils#getColumnIndex so it converts tabs to four spaces by default but there is one override that lets you choose your own tab behavior. Hopefully this should work for you, the Issue376 test case looks ok now on my side.

**Comment by lolo101** [comment]
Ok, I understand the main issue is that TabBehavior is bound to the TextGraphics and cannot be retrieved before the `draw` method is called, however the calculation of bound happens before and therefore the TabBehavior cannot be known at that moment.
