### ISSUE TITLE
TextBox background color

### ISSUE THREAD

**Issue by pablocaviglia** [mabe02/lanterna#409]
Hi, is there any way to set the background color of a TextBox component?

**Comment by avl42** [comment]
Setting colors for most widgets is done with Themes. Have a look at class
ThemeTest in the test-tree of lanterna sources for some inspiration on what
you can achieve with themes.

**Comment by mabe02** [comment]
I had decided against adding extra overriding setABCDForegroundColor/setABCDBackgroundColor methods to all the components because there would be a lot of them and since you can assign a custom theme to an individual component it didn't seem necessary.

However, when I tried to type up an example of this I noticed that while possible, it does require a lot of code just to override the theme and make the background red. So I'm going to add some helper classes to make it easier to extend a theme to just change a single property.

**Comment by mabe02** [comment]
I had decided against adding extra overriding setABCDForegroundColor/setABCDBackgroundColor methods to all the components because there would be a lot of them and since you can assign a custom theme to an individual component it didn't seem necessary.

However, when I tried to type up an example of this I noticed that while possible, it does require a lot of code just to override the theme and make the background red. So I'm going to add some helper classes to make it easier to extend a theme to just change a single property.

**Comment by pablocaviglia** [comment]
Thx! Very useful. As you said, it can be done with what we have now, but
it's not easy.

Thanks

**Comment by mabe02** [comment]
Please see Issue409 class in tests, it outlines how to use the new DelegatingTheme class to easily override the current theme and set a particular property.

**Comment by l0co** [comment]
I'm putting the example [here](https://github.com/mabe02/lanterna/blob/master/src/test/java/com/googlecode/lanterna/issue/Issue409.java) to avoid searching it in the future.
