### ISSUE TITLE
Reverse Tab (Shift + Tab) Not Automatically Handled within AbstractInteractableComponent

### ISSUE THREAD

**Issue by rxdps93** [mabe02/lanterna#412]
This is more of an inconvenience than a bug, so apologies if this does not belong here.

In `AbstractInteractableComponent` the `handleKeyStroke` method performs a check for if Alt, Control, or Shift is down before handling input. This isn't a showstopper because it can be overridden, however unless I have missed something it means that in order to simply Reverse Tab (Shift + Tab on every keyboard I've ever used) you are required to develop a workaround.

The scenario in which this impacts me is I have 3 tables and I wish to be able to Tab to move focus to the next table, or Shift + Tab to move focus to the previous table. Tab obviously works just fine, but ReverseTab was not working. The only two ways I have found to get around this are:

1. Create my own InputFilter, replace the KeyStroke with one that contains a KeyType of ReverseTab but without shift flagged as being down, and passing that to `handleKeyStroke`.
2. Create my own Table, extending the existing one, and then overwriting the `handleKeyStroke` method in order to return `MOVE_FOCUS_PREVIOUS` instead of `UNHANDLED`.

I ended up going with route number 2, which was quite simple to implement, but it just stroke me as odd that a KeyType which requires Shift on most (if not all) modern keyboards is ignored if Shift is pushed down.

**Comment by avl42** [comment]
I think the combination shift+ReverseTab shouldn't ever exist in a KeyStroke.  Whenever shift+Tab gets "encoded" into a ReverseTab KeyStroke, the "shift" ought to be cancelled.

That would be in  com.googlecode.lanterna.terminal.swing.GraphicalTerminalImplementation  line 934 in the "isShiftDown" branch:
   keyQueue.add(new KeyStroke(KeyType.ReverseTab, ctrlDown, altDown, **false**));
I'll likely create a PR soon.

ANSITerminal seems to already work, because terminal emulators just send ^[[Z for Shift-Tab.

**Comment by avl42** [comment]
Thanks, @rxdps93 for spotting&reporting it.  We now have to wait for @mabe02  to merge it.

**Comment by mabe02** [comment]
Ah, yes! Strange, why didn't we spot that earlier...
