### ISSUE TITLE
custom input

### ISSUE THREAD

**Issue by JoJpeg** [mabe02/lanterna#557]
Hey guys, sorry in advance I tried everything to find information on this. 
If i call terminal.readInput(), I will take the input that is supposed to go to the terminal right? 
How can i reach it back to the Terminal after I handled it? For now the whole program freezes because i steal that poor thing every KeyStroke it gets. 

I want do implement some custom behaviour for my program to control it via numpad only on a raspberry. 
I got it working with the SwingTerminalFrame by calling addInput() but the UnixTerminal does not implement that method.
I hope I have not missed anything very obvious. Thanks for your time!

**Comment by avl42** [comment]
"it depends"

it depends on what kind your application is.   If it is based on Terminal,
then reading input of Terminal is fine.

otherwise, it might be based on Screen if your app uses the double-buffered
Screen-layer of lanterna.
in that case, you should among the methods in Screen to find the one to
read Input from - the difference
here is, that the screen might handle some keystrokes directly, and only
pass on the rest. That way it
can e.g. still do scrolling for too small terminal-windows.

If, however you use the TextGui components, then it works completely
differently:  You no longer actively
read input, but instead have the Gui-classes handle input, or arrange to
have custom callbacks called,
if input is received from user.

If this wasn't what you meant by "take the input that is supposed to go to
the terminal", then please
clarify - or hope&wait for other replies... ;-)

**Comment by JoJpeg** [comment]
Ok i just found the solution:
You gotta send the KeyStroke to the Window not to the Terminal. In my case it was the MultiWindowTextGUI.handleInput() method that did the trick.  
Thank you @avl42 for the heads up that i have to interact with the GUI classes 🙏  

And i already foolishly injected my own InputDecoder to the StreamBasedTerminal via Java Reflections 😭
