### ISSUE TITLE
Control characters support

### ISSUE THREAD

**Issue by mitrakov** [mabe02/lanterna#567]
In MacOS, in iTerm2 terminal there is a feature to draw images [directly to terminal](https://iterm2.com/documentation-images.html).
All you need to do is to print a message in special format, like this:
```java
final String base64 = "base64-encoded-image-here";
final String s = "]1337;File=inline=1;width=100%%;height=100%%:" + base64;
Terminal terminal = new DefaultTerminalFactory().createTerminal();
terminal.putCharacter('\033');     // <--
terminal.putString(s);
terminal.putCharacter('\007');     // <--
terminal.flush();
```

But it doesn't seem to be working. It just prints `s` and ignores control characters (\033 and \007).
So does Lanterna support control characters?

**Comment by avl42** [comment]
sorry, the File=inline=1;... is fine by the spec, but the doubling of
percent chars surprises me next...   is the string used with
String.format(...) lateron? If so, then fine, otherwise, single percent
chars might be better...

Andreas Leitgeb ***@***.***> schrieb am Mi., 12. Okt. 2022, 00:24:

**Comment by mitrakov** [comment]
@avl42 , I tried single `%` but it doesn't work. It just prints the text "as is".
Moreover, if I use the same text in a bash script, it works as expected.
So the problem is definitely in the way Lanterna processes `\033` and `\007` characters

**Comment by avl42** [comment]
Another things, you could try:

- just include the Esc char (as \033) into the full string, rather than
writing it with a separate call.

- write a java/lanterna program that writes a simpler sequence, like   Esc,
'[', '1', 'm' and see if following text gets printed bold.

- pipe your command to a hexdump utility, or run it after starting
"script", then exit script, and see what the java program really writes out.

This could help diagnose the problem.

**Comment by mabe02** [comment]
Stale
